=== cngshow/isaac_rest/src/main/java/gov/vha/vets/term/services/util/WeblogicConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 sp2 (http://www.altova.com) by Brent Jacox (Dept of Veterans Affairs) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Config">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="Environment">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="DataSource">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Name" type="xs:string" nillable="false"/>
										<xs:element name="url" type="xs:string" nillable="false"/>
										<xs:element name="serverName" type="xs:string" nillable="false"/>
										<xs:element name="sid" type="xs:string" nillable="false"/>
										<xs:element name="userName" type="xs:string"/>
										<xs:element name="password" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="Name" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== cngshow/isaac_rest/src/main/java/gov/vha/vets/term/services/util/WeblogicConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2007 sp2 (http://www.altova.com)-->
<Config xsi:noNamespaceSchemaLocation="WeblogicConfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Environment Name="Dev - VTSTESTBJ">
		<DataSource>
			<Name>Deployment2</Name>
			<url>jdbc:bea:oracle://</url>
			<serverName>vhaislbll13</serverName>
			<sid>etsd03</sid>
			<userName>vtstestbj</userName>
			<password>vtstestbj</password>
		</DataSource>
		<DataSource>
			<Name>Services</Name>
			<url>jdbc:bea:oracle://</url>
			<serverName>vhaislbll13</serverName>
			<sid>etsd03</sid>
			<userName>vtstestbj</userName>
			<password>vtstestbj</password>
		</DataSource>
		<DataSource>
			<Name>Vuid</Name>
			<url>jdbc:bea:oracle://</url>
			<serverName>vhaislbll13</serverName>
			<sid>etsd03</sid>
			<userName>vtstestbj</userName>
			<password>vtstestbj</password>
		</DataSource>
	</Environment>
	<Environment Name="Local - VTSTESTBJ">
		<DataSource>
			<Name>Deployment2</Name>
			<url>jdbc:bea:oracle://</url>
			<serverName>localhost</serverName>
			<sid>STSBJ</sid>
			<userName>vtstestbj</userName>
			<password>vtstestbj</password>
		</DataSource>
		<DataSource>
			<Name>Services</Name>
			<url>jdbc:bea:oracle://</url>
			<serverName>localhost</serverName>
			<sid>STSBJ</sid>
			<userName>vtstestbj</userName>
			<password>vtstestbj</password>
		</DataSource>
		<DataSource>
			<Name>Vuid</Name>
			<url>jdbc:bea:oracle://</url>
			<serverName>localhost</serverName>
			<sid>STSBJ</sid>
			<userName>vtstestbj</userName>
			<password>vtstestbj</password>
		</DataSource>
	</Environment>
	<Environment Name="INT - VTS_V09">
		<DataSource>
			<Name>Deployment2</Name>
			<url>jdbc:bea:oracle://</url>
			<serverName>VHAISLBLL26.VHA.MED.VA.GOV</serverName>
			<sid>STSI01</sid>
			<userName>VTS_V09</userName>
			<password>vts_v09</password>
		</DataSource>
		<DataSource>
			<Name>Services</Name>
			<url>jdbc:bea:oracle://</url>
			<serverName>VHAISLBLL26.VHA.MED.VA.GOV</serverName>
			<sid>STSI01</sid>
			<userName>DS_V09</userName>
			<password>ds_v09</password>
		</DataSource>
		<DataSource>
			<Name>Vuid</Name>
			<url>jdbc:bea:oracle://</url>
			<serverName>VHAISLBLL26.VHA.MED.VA.GOV</serverName>
			<sid>STSI01</sid>
			<userName>VUID_V09</userName>
			<password>vuid_v09</password>
		</DataSource>
	</Environment>
</Config>
